["baseline-fl"]
num_rounds = 3
clients_qtd = 2
epochs = 1

["new_ckks-fl"]
num_rounds = 3
clients_qtd = 2
epochs = 1

["full_ckks-fl"]
num_rounds = 3
clients_qtd = 2
epochs = 1

["selective_ckks-fl"]
num_rounds = 3
clients_qtd = 2
epochs = 1
